//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinEmote.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class CustomKeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static CustomKeys defaultInstance = ((CustomKeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CustomKeys())));
        
        public static CustomKeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::System.Windows.Forms.Keys MidUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MidUp"]));
            }
            set {
                this["MidUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::System.Windows.Forms.Keys MidDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MidDown"]));
            }
            set {
                this["MidDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.Keys MidLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MidLeft"]));
            }
            set {
                this["MidLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Forms.Keys MidRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MidRight"]));
            }
            set {
                this["MidRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Back")]
        public global::System.Windows.Forms.Keys BackLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BackLeft"]));
            }
            set {
                this["BackLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public global::System.Windows.Forms.Keys BackRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BackRight"]));
            }
            set {
                this["BackRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::System.Windows.Forms.Keys BackUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BackUp"]));
            }
            set {
                this["BackUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::System.Windows.Forms.Keys Push {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Push"]));
            }
            set {
                this["Push"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys Setting {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
